### ISSUE TITLE
Running the project fails

### ISSUE THREAD

**Issue by n0um3n4** [iceror/to-do-app#1]
Hi there,

I'm trying to run the project so I can give you feedback (I'm part of the devs who are reviewing your project from Hopscotch).

I think something got messed up. The package.json at the root level is missing libraries. I added the necessary libraries which looks similat to the commit [#74ae14](https://github.com/iceror/to-do-app/commit/74ae14651287e97847be8c0f75a344b874e6d5a8). 
After that, the app runs just fine but now we stumbled upon another issue. At the frontend you get the error: `tasks is not defined`. This happens because the frontend assumes the backend is living at port 3000. if I run the project, it automagically points to port 4000 which causes the failing.

Once i fix that, all goes just fine, the whole projects just works complete.

Do you want to make changes for more friendly install?

**Comment by iceror** [comment]
Hey @thelastinuit , sorry for the issue.

I've made some changes to make the install process friendlier.
If you've already cloned the repo, you can pull the recent changes, run *npm
i *and *npm run start*, and the project should start smoothly!

https://github.com/iceror/to-do-app

*Note: if you have port 3000 running, you might need to close it while you
review my app.

Ilse

**Comment by n0um3n4** [comment]
> Hey @thelastinuit , sorry for the issue. I've made some changes to make the install process friendlier. If you've already cloned the repo, you can pull the recent changes, run *npm i *and *npm run start*, and the project should start smoothly! https://github.com/iceror/to-do-app *Note: if you have port 3000 running, you might need to close it while you review my app. Ilse

![](https://media.giphy.com/media/1iW2fxpFaoVNLQvS/giphy.gif)

let me see!

**Comment by n0um3n4** [comment]
![](https://media.giphy.com/media/3knKct3fGqxhK/giphy.gif)

it just worked! Excellent!
